### ISSUE TITLE
有几个小问题

### ISSUE THREAD

**Issue by goxofy** [caryyu/jellyfin-plugin-opendouban#1]
第一个是建议在readme里面介绍一下配置容器间的api地址，不然很多小白估计搞不定

第二个是，这个opendouban貌似削刮出来的电影，同名问题处理得木有官方好

第三个，不知道是不是我操作不对，我这边削刮出来的演员永远只有三个。。

**Comment by dlovew** [comment]
刚刚使用，目前演员刮削有问题！演员识别不全，且没有演员介绍！

**Comment by caryyu** [comment]
Hi @goxofy，非常抱歉那么晚才回复，Github 的通知我没有处理好现在才看见；同时也非常感谢你提出的问题，针对你的问题回答如下：

1. 好的；另外，如果你有什么好的文档排版建议的话也可以直接修改 README.md 提 PR 哦；

2. 能否把该问题更加具体一些，因为你可以根据具体的名字或 `DoubanId` 进行精确查找，我没有看明白这个问题的点；

3. 针对演员的问题是因为目前的处理规则是只抓取了详情页面中的 “导演” 和 “演员” ，没有展开演员表的页面进行处理，后面考虑可以追加上这个功能（但其实演员表的列表有些电影非常多，这边后面依然还是会需要做一些数量的限制，目前能够想到的就是限制到 15 个左右）

**Comment by caryyu** [comment]
@dlovew 目前演员介绍没有添加，这周争取迭代一个版本出来。

**Comment by caryyu** [comment]
An update: 服务端的实现扩展 https://github.com/caryyu/douban-openapi-server/pull/2

**Comment by goxofy** [comment]
赞！

**Comment by caryyu** [comment]
Update: 该 PR https://github.com/caryyu/jellyfin-plugin-opendouban/pull/2 一旦合并发布之后就支持了，还请耐心等待，还有待测试。

**Comment by caryyu** [comment]
Update: `v1.0.5` 版本已发布并解决了该问题，在更新插件之前确保 `caryyu/douban-openapi-server:67f97ed` 服务端版本与之对应，先关闭该 Issue 了，有新的问题请重新提，谢谢反馈！
