### ISSUE TITLE
发现插件缺少一些数据或功能，会考虑增加吗？

### ISSUE THREAD

**Issue by cxfksword** [caryyu/jellyfin-plugin-opendouban#12]
1、缺少电影和TV缺少风格数据
2、TV不显示豆瓣外链
![](https://cdn.jsdelivr.net/gh/cxfksword/assets@master/img/1633076678080iShot2021-10-01%2016.23.36.jpg)

3、不支持配置下载季封面图
![](https://cdn.jsdelivr.net/gh/cxfksword/assets@master/img/1633076682870iShot2021-10-01%2016.24.17.jpg)

**Comment by caryyu** [comment]
@cxfksword 针对 2 外链问题是支持的，可以参考 https://github.com/caryyu/jellyfin-plugin-opendouban/blob/master/Jellyfin.Plugin.OpenDouban/Providers/ExternalId/OddbMovieExternalId.cs

另外，非常感谢对于需求 1 和 3 的提出，后面会进行迭代的，请持续关注。。。

**Comment by cxfksword** [comment]
movie和season是有外链的，我是指series缺少了（即进入电视剧显示季数那页面），现在只有themoviedb的显示，opendouban的没显示

**Comment by caryyu** [comment]
@cxfksword 好的，明白了；该 Issue 关联 PR 我先测试一下，通过之后我会直接发版并且该 Issue 会被关闭，如果问题依然重现请重新打开，谢谢。
