### ISSUE TITLE
Jellyfin 10.8.0-alpha 兼容问题

### ISSUE THREAD

**Issue by kfcceo** [caryyu/jellyfin-plugin-opendouban#19]
绝了，emby的豆瓣插件能用，jell的都不能用了？

**Comment by caryyu** [comment]
@kfcceo 能把你使用的版本号发我一下吗？目前已知的是在 Jellyfin 10.8.x 中该插件是无法使用的，因为官方 10.8.x 是一个跨越性的变更，还在 Alpha 的初级阶段。

**Comment by caryyu** [comment]
Hi @kfcceo ，经过测试，目前版本不兼容 `Jellyfin 10.8.0-alpha` 系列，请耐心等待兼容版本放出。

**Comment by kfcceo** [comment]
感谢大神

发自我的iPhone

**Comment by caryyu** [comment]
最新进展跟踪： https://github.com/caryyu/jellyfin-plugin-opendouban/pull/20

**Comment by caryyu** [comment]
已经解决，请使用 v2.x.x 插件版本。
