### ISSUE TITLE
【IP异常检测】 可否增加接口查询间隙时间

### ISSUE THREAD

**Issue by virualv** [caryyu/jellyfin-plugin-opendouban#28]
> 用一次豆瓣就提示ip异常了
> 可否增加一个接口查询间隙时间配置
> 或者添加一个10s内的随机时间值作为每次查询间隔，来降低被侦测

**Comment by caryyu** [comment]
@virualv 目前暂不支持，后面可以考虑扩展一下，只能等待解封了，一般等几个小时就好了。

**Comment by caryyu** [comment]
@virualv 目前服务端启动参数可以支持设置 Cookie 了，意味着可以自行在浏览器登录进去，然后利用 Chrome 的插件获取 Cookie 设置到服务端即可跳过 IP 异常检测（据我所知，登录的用户豆瓣是不会进行限制拦截的！）

> Tip: 请纠正我，如果我说的不对，谢谢 :)

**Comment by virualv** [comment]
可以，但是豆瓣反爬严格。如果直接登录后接口访问过度频繁不确定会不会封禁账户

**Comment by caryyu** [comment]
@virualv 如果某次 API 调用超过间隙时间那 API 返回值应该是空还是 Pending 住？如果是后者，那么请求的并发数也有存在被超过的问题，最终都会直接反应到客户端，最后导致客户端的搜刮会是失败的，本质均会导致客户端搜刮产生问题；不知道你那边有没有更好的建议。

**Comment by virualv** [comment]
设置调用间隙时间的目的是降低访问豆瓣的频次，避免高频访问豆瓣触发豆瓣自身保护机制而被短时封禁。如果服务端 API
如果是接收到一次调用去访问一次豆瓣，那么调用延时在客户端做就已经可以达到效果了，不必要在服务端做。这样也只是延长了刮削时间，不会影响到正常刮削。

: ask me anything :) ***@***.***> 于2022年7月25日周一 19:14写道：

**Comment by caryyu** [comment]
@virualv 插件目前都是被动接收到 Jellyfin 下发的搜刮调用命令以同步方式进行的，如果 Pending 插件的同步操作我猜测 Jellyfin 也有超时限制的（没具体研究过），没想明白插件如何做到延时来调用（进行大量堵塞嘛？）。

**Comment by virualv** [comment]
Libitum/jellyfin-plugin-douban里有用到最小请求间隔，但是我不会C#所以没法帮你捋清它的实现逻辑，你可以参考一下这个

: ask me anything :) ***@***.***> 于2022年7月27日周三 21:30写道：

**Comment by caryyu** [comment]
@virualv 你应该指的是这个： https://github.com/Libitum/jellyfin-plugin-douban/blob/master/Jellyfin.Plugin.Douban/Configuration/PluginConfiguration.cs#L11 

这个参数我在它的仓库全局搜索了一下并没有找到引用的地方，我猜应该没有使用到，照理说插件很难自己来定义搜刮频率，该频率应该由 Jellyfin 的主 Server 来决定。
