### ISSUE TITLE
插件无法正常工作

### ISSUE THREAD

**Issue by CoolLoong** [caryyu/jellyfin-plugin-opendouban#29]
可以帮我解决一下吗，已经配置了douban api server
Jefflyfin是用docker 的 nyanmisaka/jellyfin:latest镜像

**Comment by CoolLoong** [comment]
[jellyfin日志](https://paste.liumingye.cn/5560)

**Comment by caryyu** [comment]
@CoolLoong  下述日志已经说明了情况，你插件安装之后没有正确配置 Server 端，你可以试试调试 Server 端的 API 接口：

```txt
[2022-03-17 11:58:29.874 +08:00] [ERR] [33] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "OpenDouban"
System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:5000)
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
```

追加：把 `localhost:5000` 配置成 Server 端的 IP 地址。

**Comment by CoolLoong** [comment]
![image](https://user-images.githubusercontent.com/69153398/158757146-07247e19-5c70-45d0-8d31-24c6235d9aef.png)
我之前就已经添加了我本地的server地址，没有什么效果

**Comment by caryyu** [comment]
@CoolLoong 你是否尝试过利用 curl 单步调试接口是否可以正常工作，看看 Server 端有没有错误日志等等。
