### ISSUE TITLE
检索国产电视剧搜索的都不对，用豆瓣id可以检索到

### ISSUE THREAD

**Issue by dnpl** [caryyu/jellyfin-plugin-opendouban#30]
server日志中怎么都是--，无法看到检索的关键字到底是不是对的。无论新老电视剧，输入名字基本得不到有用的信息，好多是错误。
![log](https://user-images.githubusercontent.com/22452022/159096681-7e5e8988-0e0b-48bb-8fa8-d7aec4ac6149.jpg)

**Comment by caryyu** [comment]
@dnpl 感谢你的反馈，电视剧的关键字搜索目前 Server 端暂不支持，请耐心等待后续开发 :)

**Comment by dnpl** [comment]
> @dnpl 感谢你的反馈，电视剧的关键字搜索目前 Server 端暂不支持，请耐心等待后续开发 :)

你好，我用的以前是可以的，只是最近不行了。

**Comment by caryyu** [comment]
@dnpl 嗯，因为豆瓣的关键字搜索功能之前变更过，所以后来针对电影类别搜索做了修复，还没来得及修复电视剧搜索。

**Comment by dnpl** [comment]
> @dnpl 嗯，因为豆瓣的关键字搜索功能之前变更过，所以后来针对电影类别搜索做了修复，还没来得及修复电视剧搜索。

近期有希望修复该功能吗

**Comment by caryyu** [comment]
@dnpl 能否把上述截图中的日志对于关键字搜索部分进行贴一些示例出来，我这一段时间尝试测试及修复一下。

**Comment by dnpl** [comment]
搜索电视剧基本搜索不到内容，日志看到的信息都是显示的“-”

**Comment by caryyu** [comment]
@dnpl 该问题属于 Server 端问题，我在 Server 端新开了一个 Issue 跟踪：https://github.com/caryyu/douban-openapi-server/issues/19 ，该 Issue 我先关了。
