### ISSUE TITLE
能不能搞一个emby版的插件

### ISSUE THREAD

**Issue by youyifentian** [caryyu/jellyfin-plugin-opendouban#31]
好像emby版的跟jellyfin的差别不是很大，之前也有一个
https://github.com/AlifeLine/Emby.Plugins.Douban

但是这个有时候会挂不出来，想问问大佬能不能修改下，

**Comment by caryyu** [comment]
@youyifentian 非常感谢你的反馈，我这边还没有玩过 Emby ，我有空的时候参照手册试试；目前初步看了一下该插件开发策略声明：https://github.com/MediaBrowser/Emby/wiki/Development-Policy ，关于 Catalog 仓库不知道是否支持自定义 Server 端，后面研究一下。

**Comment by youyifentian** [comment]
> @youyifentian非常感谢你的反馈，我当时还没有玩过 Emby，我有插件开发使用手册使用的时间；现在，我看你的策略是：[https ://github.com/MediaBrowser/Emby/ wiki/Development-Policy](https://github.com/MediaBrowser/Emby/wiki/Development-Policy)，关于目录仓库不支持自定义服务器端，后面研究一下。

好的，非常感谢，希望可以支持，

另外，还有一个小姐姐刮削插件，emby和jellyfin通用的，他的就可以调用代理服务来刮削，应该是可以实现，
不过我对这也不懂，你可以看看，这是地址
https://github.com/JavScraper/Emby.Plugins.JavScraper

**Comment by leeyonwang** [comment]
大佬，请问emby版的插件有进度了吗？
之前就用你的插件 昨天换到emby了，那边豆瓣的插件已经不可用，不知道你的插件，emby版本有了吗？

**Comment by caryyu** [comment]
@leeyonwang 建议使用开源版本的 `Jellyfin` 并共同在此项目上进行贡献；遇到使用上的问题可以到相应社区留言，这样可以一起有益于帮助社区成长，谢谢。

> Tip: 对于 Emby 据我所知是闭源之后才诞生的 Jellyfin ，鉴于此，对于该项目的开源劳动投入长期来说是无意义的。
