### ISSUE TITLE
动画类抓取后没法显示演员表

### ISSUE THREAD

**Issue by cxfksword** [caryyu/jellyfin-plugin-opendouban#35]
看了下好像是动画类返回的role是配音，而jellyfin只显示role是演员的导致，是不是把接口的PersonType和Role字段拆开更好？

**Comment by caryyu** [comment]
@cxfksword 感谢你的使用反馈，能否把相应的资源链接发一下，供我这边调试，谢谢。

**Comment by cxfksword** [comment]
@caryyu 我测试好像所有日本动画都是这样，其中一个：
https://movie.douban.com/subject/1421721/

**Comment by caryyu** [comment]
@cxfksword 照理说应该是支持配音的，可以看这里：https://github.com/caryyu/douban-openapi-server/blob/main/provider/httprequest_provider.py#L122 

另外，你可以手动调用接口调试一下把返回的结果正确性检查一下。

**Comment by cxfksword** [comment]
看了下是jellyfin做了限制，他过滤了type不是演员的，而动画类接口返回了配音，导致被过滤了

https://github.com/jellyfin/jellyfin-web/blob/7660bc606db70e623da83c5883a8c15c34c38ad0/src/controllers/itemDetails/index.js#L1826

**Comment by caryyu** [comment]
@cxfksword 也就是说除了导演其它的设置成演员，具体看这里的逻辑：https://github.com/caryyu/jellyfin-plugin-opendouban/blob/10.8.x-main/Jellyfin.Plugin.OpenDouban/Providers/OddbMovieProvider.cs#L157 

因为 PersonType 不支持配音角色：https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Model/Entities/PersonType.cs/

**Comment by cxfksword** [comment]
是的，要设为演员，不然会被过滤

**Comment by caryyu** [comment]
@cxfksword 最新版本已经修复，我先关闭该 Issue 了，有问题再重开，谢谢。
