### ISSUE TITLE
插件链接失效

### ISSUE THREAD

**Issue by dnpl** [caryyu/jellyfin-plugin-opendouban#45]
https://github.com/caryyu/jellyfin-plugin-repo/raw/master/manifest-us.json

这个链接无法访问，无法在jellyfin安装插件了

**Comment by caryyu** [comment]
@dnpl 改地址是境外的，无法直接使用！原来采用 https://gitee.com/caryyu/jellyfin-plugin-repo/raw/master/manifest-cn.json 这个，但是后来 Gitee 关闭了托管。

**Comment by caryyu** [comment]
@dnpl  有好的替代品请在下列 Issue 跟踪及反馈，谢谢！

https://github.com/caryyu/jellyfin-plugin-opendouban/issues/38
