### ISSUE TITLE
这个插件安装后搜索不到元数据

### ISSUE THREAD

**Issue by dajiangfu** [caryyu/jellyfin-plugin-opendouban#48]
如题，请问是因为还要进行配置吗，具体不太懂这个怎么配置，希望大佬能出个详细教程，或者操作视频录屏也可以，谢谢！

**Comment by caryyu** [comment]
@dajiangfu 需要同时设置 Server 端的，然后可以在设置面板指定 Server 端的地址。

**Comment by dajiangfu** [comment]
谢谢！大概明白了
