### ISSUE TITLE
GitHub源 安装报错： Only zip packages are supported

### ISSUE THREAD

**Issue by zexindai** [caryyu/jellyfin-plugin-opendouban#7]
先尝试了GitHub源
系统报如下的错误：
` [ERR] Only zip packages are supported. "https://github.com/caryyu/jellyfin-plugin-repo/blob/master/Jellyfin.Plugin.OpenDouban.1.0.7.zip?raw=true" is not a zip archive.`

切换成gitee源则成功

猜测是因为GitHub源的文件末尾多了“raw=true”

**Comment by caryyu** [comment]
@zexindai 可能是网络下载不全导致的问题；理论上两个压缩包应该是相同的，你可以分别打开下面两个具体压缩包位置对比一下大小，其实是一样的：

https://github.com/caryyu/jellyfin-plugin-repo/blob/master/Jellyfin.Plugin.OpenDouban.1.0.7.zip
https://gitee.com/caryyu/jellyfin-plugin-repo/blob/master/Jellyfin.Plugin.OpenDouban.1.0.7.zip

**Comment by zexindai** [comment]
> @zexindai 可能是网络下载不全导致的问题；理论上两个压缩包应该是相同的，你可以分别打开下面两个具体压缩包位置对比一下大小，其实是一样的：
> 
> https://github.com/caryyu/jellyfin-plugin-repo/blob/master/Jellyfin.Plugin.OpenDouban.1.0.7.zip
> https://gitee.com/caryyu/jellyfin-plugin-repo/blob/master/Jellyfin.Plugin.OpenDouban.1.0.7.zip

我看的是这个：https://raw.githubusercontent.com/caryyu/jellyfin-plugin-repo/master/manifest-us.json
里面的文件有“raw=true”

另外想请问一下，是不是本地要运行douban-openapi-server才可以使用这个插件？

**Comment by caryyu** [comment]
@zexindai 你看的那个文件是 Jellyfin 的配置清单文件，实际上会从我上述的两个压缩包的地方下载；对的，该插件依靠 server 端的服务，你需要在本地同时启动的。

**Comment by zexindai** [comment]
> @zexindai 你看的那个文件是 Jellyfin 的配置清单文件，实际上会从我上述的两个压缩包的地方下载；对的，该插件依靠 server 端的服务，你需要在本地同时启动的。

好的 了解了 感谢！
